language: node_js
node_js:
- '8'

#cache:
#  directories:
#    - node_modules

install:
  - npm install qxcompiler -g 
  - npm install 
  - git clone --depth 1 https://github.com/qooxdoo/qooxdoo.git

script:
  - ./generate.py api
  - mkdir -p api/qx/icon
  - mv qooxdoo/framework/source/resource/qx/icon/Tango api/qx/icon/Tango
  - qx compile --target=build
  - mv api build-output/
  - mv 
  - find build-output -name ".gitignore" -type f -delete
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build-output
  on:
    branch: master
