language: node_js

#cache:
#  directories:
#    - node_modules

install:
  - npm install -g qooxdoo-compiler
  - npm install 
  - git clone --depth 1 https://github.com/qooxdoo/qooxdoo.git

script:
  - qx compile --target=build
  - ./generate.py api
  - mv api build-output/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build-output
  on:
    branch: master